### ISSUE TITLE
"most of the time use chaining"?

### ISSUE THREAD

**Issue by jonschlinkert** [node-base/base-compose#2]
lol, I was getting errors when trying to chain methods. some work, some don't. is there a reason the API isn't consistent? https://github.com/node-base/base-compose/blob/master/lib/composition-handler.js#L77

edit: the issue title is a quote from the readme docs

**Comment by jonschlinkert** [comment]
I'm pushing up changes in a bit...

**Comment by doowb** [comment]
lol... what you linked to was a mistake (the code comment says that it returns `this` for chaining).

The comment in the example should probably be something like `// or use chaining` or something to better describe that it's not necessary to store the results in a variable, then call methods on the variable... or just remove the first line and comment from that example.

**Comment by jonschlinkert** [comment]
> lol... what you linked to was a mistake

yeah I know, I was just pointing it out. sorry I thought you knew what I meant

**Comment by doowb** [comment]
The changes look good. I made one comment around `data` in regards to #1. I'll close this issue and we can discuss on that other issue.
